apiVersion: batch/v1
kind: Job
metadata:
  name: billing-on-demand
  namespace: default
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: 3600
  template:
    metadata:
      labels:
        app: billing-aggregation
    spec:
      serviceAccountName: spark-serviceaccount
      restartPolicy: Never
      volumes:
        - name: app-env
          configMap:
            name: app-env
        - name: aws-creds
          secret:
            secretName: aws-creds
        - name: spark-event-logs
          emptyDir: {}
        - name: spark-upload
          emptyDir: {}
        - name: fluent-bit-config
          configMap:
            name: fluent-bit-config
        - name: var-log-containers
          hostPath:
            path: /var/lib/docker/containers
            type: Directory
      containers:
        - name: spark-submit
          image: distributed-billing-spark:latest
          imagePullPolicy: IfNotPresent
          workingDir: /app
          env:
            - name: SPARK_CONF_spark.kubernetes.container.image
              value: distributed-billing-spark:latest

            - name: SPARK_CONF_spark.kubernetes.authenticate.driver.serviceAccountName
              value: spark-serviceaccount

            - name: SPARK_CONF_spark.kubernetes.file.upload.path
              value: /tmp/spark-upload
          envFrom:
            - configMapRef:
                name: app-env
            - secretRef:
                name: aws-creds
          volumeMounts:
            - name: spark-event-logs
              mountPath: /app/logs/spark-events
            - name: spark-upload
              mountPath: /tmp/spark-upload
          command: ["/bin/bash", "-c", "/app/scripts/submit_spark_job.sh"]
        - name: fluent-bit
          image: amazon/aws-for-fluent-bit:latest
          imagePullPolicy: IfNotPresent
          env:
            - name: AWS_REGION
              valueFrom:
                secretKeyRef:
                  name: aws-creds
                  key: AWS_REGION
          volumeMounts:
            - name: spark-event-logs
              mountPath: /app/logs/spark-events
            - name: var-log-containers
              mountPath: /var/lib/docker/containers
              readOnly: true
            - name: fluent-bit-config
              mountPath: /fluent-bit/etc
