apiVersion: v1
kind: Service
metadata:
  name: spark-master-ui
  namespace: default
spec:
  type: NodePort
  selector:
    app: spark-master
  ports:
    - name: ui
      port: 8080
      targetPort: 8080
      nodePort: 30080