apiVersion: v1
kind: Service
metadata:
  name: spark-history-ui
  labels:
    app: spark-history
spec:
  type: ClusterIP
  ports:
    - port: 18080
      targetPort: 18080
      name: http
  selector:
    app: spark-history
